### ISSUE TITLE
Image doesn't build with kibana:5.0.0

### ISSUE THREAD

**Issue by jessalfredsen** [AntoineReneleau/docker-sense#1]
Hey man. Cool repo, and _*just*_ what I was looking for. Thanks.

Just letting you know that the image doesn't build with the latest 5.0.0 version of kibana.

`FROM kibana:4.6.2` works fine :)

Would've made a PR but no access :(

Cheers,
Jess

**Comment by AntoineReneleau** [comment]
Hey,

I'm happy you found a use for this project :slightly_smiling_face: 
Thanks for bringing this up. I made a PR to fix the issue.
(You can fork the repo to make PRs :slightly_smiling_face: )

Cheers,
Antoine

**Comment by jessalfredsen** [comment]
Ahh yes.. I'll fork the next time :)
/J
